security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

    # Contrôle d'accès en fonction des rôles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/librarian, roles: ROLE_LIBRARIAN }
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_LIBRARIAN: ROLE_USER
        ROLE_ADMIN: [ROLE_LIBRARIAN]